## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

theme = "hugo-story"
title = "Jakub Matyjaszek"
copyright = "{year}"

relativeURLs = "true"



baseURL = "https://matyjaszek.github.io/"
publishDir = "public"




disableKinds = ["taxonomy", "taxonomyTerm", "section"]

[Params]

[Params.social]
  github = "https://github.com/baroksos/"
  twitter = "https://twitter.com/JakubMatyjasze1"
  email = "jakubtakephotos@gmail.com"
  instagram = "https://instagram.com/jakub.matyjaszek"
  pinterest = "https://pinterest.com/kubamatyjaszek/"


