name: Deploy Pre-built Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
  deploy:

    environment:
      name: github-pages
      url: https://barokos.github.io 
    runs-on: ubuntu-latest
   
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3



      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true